<a href="https://colab.research.google.com/github/zhangwiki86-soton/Python-Files-for-Practice/blob/main/Combining_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Combining Data
- **Pandas provides two primary ways to combine DataFrames**
    - **Concat/Append**: Stacking DataFrames either vertically (adding rows) or horizontally (adding columns).
        - ``concat()``
    - **Merge/join** Integrating DataFrames on a common key (such as primary key in DBs - SQL-style joining on keys).
        - ``merge()`` and ``join()``

### Sample Data Setup

In [ ]:
import pandas as pd
# We have two DataFrames:
# temperature_df – Daily maximum temperatures.
# humidity_df – Daily humidity levels.

temperature_data = {
    'Date': pd.to_datetime([
        '2025-01-16', '2025-01-17', '2025-01-18',
        '2025-01-19', '2025-01-20', '2025-01-21',
        '2025-01-22'
    ]),
    'Max Temperature (C)': [13.0, 14.0, 17.1, 17.8, 15.3, 13.7, 16.5]
}
temperature_df = pd.DataFrame(temperature_data)

# DataFrame containing daily humidity levels
humidity_data = {
    'Date': pd.to_datetime([
        '2025-01-16', '2025-01-17', '2025-01-18',
        '2025-01-19', '2025-01-20', '2025-01-21',
        '2025-01-23'
    ]),
    'Humidity (%)': [76, 78, 82, 86, 80, 78, 85]
}
humidity_df = pd.DataFrame(humidity_data)

In [ ]:
# Check the data frames

## 1.1 Merging Data (SQL-style)
- Combining DataFrames on a shared key(**SQL-style** join - combining by columns (or by index if you specify))
- `pd.merge(left, right, on=..., how=...)`
- **Join Types**
    - **Inner**: Keep only matching rows.
    - **Left**: Keeps **all rows** from the **left** DataFrame, filling missing values with NaN for non-matching rows.
    - **Right**: Retains all rows from the right DataFrame, filling missing values with NaN.
    - **Outer**: Retains all rows from both DataFrames, filling missing values with NaN.

> - [Top-level merging: ``pd.merge()``](https://pandas.pydata.org/docs/reference/api/pandas.merge.html)
> - [DataFrame method: ``DataFrame.merge()``](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

In [ ]:
# Merging the two DataFrames on 'Date' using an inner join (default)

In [ ]:
# Left Join

In [ ]:
# Right Join

In [ ]:
# Outer Join

In [ ]:
# DataFrame method: DataFrame.merge()

## 1.2 Joining Using DataFrame.join()
- ``join()`` is ideal for **index-based joins**; simplifying combining DataFrames that share a common index.

In [ ]:
# Set 'Date' as index for both DataFrames

In [ ]:
# inner join

In [ ]:
# left join

## 1.3 Concatenating DataFrames (`pd.concat`)
- Concatenation involves stacking DataFrames either vertically (one below the other - adding rows) or horizontally (side by side - adding columns).
- It **does not merge on a key**, it aligns columns (if appending rows) or aligns rows (if adding columns).

### 1.3.1 Vertical Concatenation (Stacking Rows)

In [ ]:
# Additional temperature readings for subsequent days
extra_data = {
    'Date': pd.to_datetime(['2025-01-23', '2025-01-24']),
    'Max Temperature (C)': [17.2, 14.8]
}
extra_df = pd.DataFrame(extra_data)

In [ ]:
# vertical concatenation

        Date  Max Temperature (C)
0 2025-01-16                 13.0
1 2025-01-17                 14.0
2 2025-01-18                 17.1
3 2025-01-19                 17.8
4 2025-01-20                 15.3
5 2025-01-21                 13.7
6 2025-01-22                 16.5
7 2025-01-23                 17.2
8 2025-01-24                 14.8

### 1.3.2 Horizontal Concatenation (Adding Columns)

In [ ]:
# a separate DataFrame with an additional metric (like `Min Temperature (C)`) for the exact same dates and rows
min_temp_data = {
    'Min Temperature (C)': [8.0, 7.5, 9.1, 9.5, 8.8, 6.2, 7.7]
}
min_temp_df = pd.DataFrame(min_temp_data)

In [ ]:
# Horizontal concatenation

        Date  Max Temperature (C)  Min Temperature (C)
0 2025-01-16                 13.0                  8.0
1 2025-01-17                 14.0                  7.5
2 2025-01-18                 17.1                  9.1
3 2025-01-19                 17.8                  9.5
4 2025-01-20                 15.3                  8.8
5 2025-01-21                 13.7                  6.2
6 2025-01-22                 16.5                  NaN